version: '3.1'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_HOST: db
            DB_USERNAME: postgres
            DB_PASSWORD: password
            DB_DATABASE: monkey
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        image: postgres:15.3-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: monkey
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data:
